/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
import { t } from '@apache-superset/core/translation';
import { validateNonEmpty } from '@superset-ui/core';
import {
  ControlPanelConfig,
  D3_FORMAT_DOCS,
  D3_FORMAT_OPTIONS,
  getStandardizedControls,
} from '@superset-ui/chart-controls';
import manifest from '../data/manifest.json';

// ----------------------------------------------------------------------
// Choice tables — sourced from the build pipeline's manifest.json
//
// The manifest is regenerated by every `./scripts/build.sh` run; adding
// a new worldview or country to the YAML configs and re-running build
// makes the new option appear in the UI without touching this file.
// ----------------------------------------------------------------------

interface CountryMapManifest {
  worldviews: string[];
  admin_levels: number[];
  countries_by_worldview: Record<string, string[]>;
  regional_aggregations: Array<{
    country: string;
    set_id: string;
    worldview: string;
    size_bytes: number;
  }>;
  composites: Array<{ id: string; worldview: string; size_bytes: number }>;
}

const M = manifest as CountryMapManifest;

// Display-name labels for worldviews. Anything not listed here renders
// as the worldview code itself in the dropdown.
const WORLDVIEW_LABELS: Record<string, string> = {
  ukr: t('Ukraine (default — Crimea as Ukrainian)'),
  default: t('Natural Earth Default'),
  ind: t('India'),
  pak: t('Pakistan'),
  chn: t('China'),
  rus: t('Russia'),
  isr: t('Israel'),
  pse: t('Palestine'),
  tur: t('Türkiye'),
  jpn: t('Japan'),
  kor: t('Korea'),
  usa: t('United States'),
  fra: t('France'),
  gbr: t('United Kingdom'),
};

const WORLDVIEW_CHOICES: Array<[string, string]> = M.worldviews.map(wv => [
  wv,
  WORLDVIEW_LABELS[wv] || wv,
]);

const ADMIN_LEVEL_CHOICES: Array<[string, string]> = [
  [String(0), t('Countries (Admin 0)')],
  [String(1), t('Subdivisions (Admin 1)')],
  ['aggregated', t('Aggregated regions')],
];

// English country names by ISO_A3, for friendly dropdown labels. Codes
// not listed here render as the raw ISO code (rare; missing entries
// here aren't a correctness problem).
const COUNTRY_LABELS: Record<string, string> = {
  AFG: 'Afghanistan',
  ARG: 'Argentina',
  AUS: 'Australia',
  AUT: 'Austria',
  BEL: 'Belgium',
  BGD: 'Bangladesh',
  BGR: 'Bulgaria',
  BIH: 'Bosnia and Herzegovina',
  BLR: 'Belarus',
  BOL: 'Bolivia',
  BRA: 'Brazil',
  CAN: 'Canada',
  CHE: 'Switzerland',
  CHL: 'Chile',
  CHN: 'China',
  COL: 'Colombia',
  CRI: 'Costa Rica',
  CUB: 'Cuba',
  CYP: 'Cyprus',
  CZE: 'Czechia',
  DEU: 'Germany',
  DNK: 'Denmark',
  DOM: 'Dominican Republic',
  ECU: 'Ecuador',
  EGY: 'Egypt',
  ESP: 'Spain',
  EST: 'Estonia',
  ETH: 'Ethiopia',
  FIN: 'Finland',
  FRA: 'France',
  GBR: 'United Kingdom',
  GHA: 'Ghana',
  GRC: 'Greece',
  GTM: 'Guatemala',
  HND: 'Honduras',
  HRV: 'Croatia',
  HUN: 'Hungary',
  IDN: 'Indonesia',
  IND: 'India',
  IRL: 'Ireland',
  IRN: 'Iran',
  IRQ: 'Iraq',
  ISL: 'Iceland',
  ISR: 'Israel',
  ITA: 'Italy',
  JPN: 'Japan',
  KAZ: 'Kazakhstan',
  KEN: 'Kenya',
  KGZ: 'Kyrgyzstan',
  KHM: 'Cambodia',
  KOR: 'South Korea',
  LAO: 'Laos',
  LBN: 'Lebanon',
  LTU: 'Lithuania',
  LVA: 'Latvia',
  MAR: 'Morocco',
  MEX: 'Mexico',
  MMR: 'Myanmar',
  MNG: 'Mongolia',
  MYS: 'Malaysia',
  NGA: 'Nigeria',
  NLD: 'Netherlands',
  NOR: 'Norway',
  NPL: 'Nepal',
  NZL: 'New Zealand',
  PAK: 'Pakistan',
  PER: 'Peru',
  PHL: 'Philippines',
  POL: 'Poland',
  PRT: 'Portugal',
  PRY: 'Paraguay',
  ROU: 'Romania',
  RUS: 'Russia',
  SAU: 'Saudi Arabia',
  SDN: 'Sudan',
  SRB: 'Serbia',
  SVK: 'Slovakia',
  SVN: 'Slovenia',
  SWE: 'Sweden',
  SYR: 'Syria',
  THA: 'Thailand',
  TUR: 'Türkiye',
  TWN: 'Taiwan',
  UKR: 'Ukraine',
  URY: 'Uruguay',
  USA: 'United States',
  UZB: 'Uzbekistan',
  VEN: 'Venezuela',
  VNM: 'Vietnam',
  YEM: 'Yemen',
  ZAF: 'South Africa',
  ZWE: 'Zimbabwe',
};

const formatCountry = (code: string): string =>
  COUNTRY_LABELS[code] ? `${COUNTRY_LABELS[code]} (${code})` : code;

// Build country choices from the union of all worldview manifests
// (typically the same set since Admin 1 is one global file, but
// future per-worldview Admin 1 outputs would naturally differ).
const COUNTRY_CHOICES: Array<[string, string]> = (() => {
  const all = new Set<string>();
  Object.values(M.countries_by_worldview).forEach(codes =>
    codes.forEach(c => all.add(c)),
  );
  return Array.from(all)
    .sort()
    .map<[string, string]>(c => [c, formatCountry(c)]);
})();

// Region-set labels keyed by `<set_id>` (TUR's `nuts_1` etc.).
const REGION_SET_LABELS: Record<string, string> = {
  nuts_1: t('NUTS-1 statistical regions'),
  regions: t('Administrative regions'),
};

// Build {country: [(set_id, label), ...]} from manifest.
const REGION_SET_CHOICES_BY_COUNTRY: Record<string, Array<[string, string]>> = (
  () => {
    const out: Record<string, Array<[string, string]>> = {};
    M.regional_aggregations.forEach(r => {
      out[r.country] = out[r.country] || [];
      out[r.country].push([
        r.set_id,
        REGION_SET_LABELS[r.set_id] || r.set_id,
      ]);
    });
    return out;
  }
)();

// Composite-map labels keyed by `<id>`.
const COMPOSITE_LABELS: Record<string, string> = {
  france_overseas: t('France (with overseas territories)'),
};

const COMPOSITE_CHOICES: Array<[string, string]> = M.composites.map(c => [
  c.id,
  COMPOSITE_LABELS[c.id] || c.id,
]);

// NE NAME_<lang> language codes available across most features.
const NAME_LANGUAGE_CHOICES: Array<[string, string]> = [
  ['en', t('English (en)')],
  ['fr', t('French (fr)')],
  ['de', t('German (de)')],
  ['es', t('Spanish (es)')],
  ['it', t('Italian (it)')],
  ['pt', t('Portuguese (pt)')],
  ['ru', t('Russian (ru)')],
  ['zh', t('Chinese (zh)')],
  ['ja', t('Japanese (ja)')],
  ['ko', t('Korean (ko)')],
  ['vi', t('Vietnamese (vi)')],
  ['ar', t('Arabic (ar)')],
  ['hi', t('Hindi (hi)')],
  ['fa', t('Persian (fa)')],
  ['tr', t('Turkish (tr)')],
  ['nl', t('Dutch (nl)')],
  ['pl', t('Polish (pl)')],
  ['sv', t('Swedish (sv)')],
  ['el', t('Greek (el)')],
  ['he', t('Hebrew (he)')],
];

// ----------------------------------------------------------------------
// Visibility helpers
// ----------------------------------------------------------------------

const isAdminCountry = (controls: Record<string, { value?: unknown }>) =>
  controls.admin_level?.value === String(0) || controls.admin_level?.value === 0;
const isAdminSubdivision = (controls: Record<string, { value?: unknown }>) =>
  controls.admin_level?.value === String(1) || controls.admin_level?.value === 1;
const isAdminAggregated = (controls: Record<string, { value?: unknown }>) =>
  controls.admin_level?.value === 'aggregated';

const config: ControlPanelConfig = {
  controlPanelSections: [
    {
      label: t('Map'),
      expanded: true,
      controlSetRows: [
        [
          {
            name: 'worldview',
            config: {
              type: 'SelectControl',
              label: t('Worldview'),
              description: t(
                'Cartographic perspective for disputed regions. ' +
                  'Defaults to Ukraine worldview (Crimea shown as Ukrainian); ' +
                  'override per-deployment in superset_config.COUNTRY_MAP.default_worldview.',
              ),
              choices: WORLDVIEW_CHOICES,
              default: 'ukr',
              renderTrigger: true,
              clearable: false,
            },
          },
        ],
        [
          {
            name: 'admin_level',
            config: {
              type: 'SelectControl',
              label: t('Admin level'),
              description: t(
                'Choose the geographic level: countries (world map), ' +
                  'subdivisions of one country, or an aggregated regional layer.',
              ),
              choices: ADMIN_LEVEL_CHOICES,
              default: String(0),
              renderTrigger: true,
              clearable: false,
            },
          },
        ],
        [
          {
            name: 'country',
            config: {
              type: 'SelectControl',
              label: t('Country'),
              description: t('Which country to plot subdivisions for.'),
              choices: COUNTRY_CHOICES,
              default: null,
              renderTrigger: true,
              clearable: false,
              validators: [validateNonEmpty],
              visibility: ({ controls }: any) =>
                !isAdminCountry(controls) && !controls.composite?.value,
            },
          },
        ],
        [
          {
            name: 'region_set',
            config: {
              type: 'SelectControl',
              label: t('Aggregated region set'),
              description: t(
                'Which administrative region layer to dissolve into. ' +
                  'Available sets depend on the selected country.',
              ),
              choices: ({ controls }: any) =>
                REGION_SET_CHOICES_BY_COUNTRY[
                  String(controls.country?.value || '')
                ] || [],
              default: null,
              renderTrigger: true,
              clearable: true,
              visibility: ({ controls }: any) => isAdminAggregated(controls),
            },
          },
        ],
        [
          {
            name: 'composite',
            config: {
              type: 'SelectControl',
              label: t('Composite map'),
              description: t(
                'Multi-country composite (e.g. France with overseas territories). ' +
                  'When set, overrides admin level + country.',
              ),
              choices: COMPOSITE_CHOICES,
              default: null,
              renderTrigger: true,
              clearable: true,
            },
          },
        ],
        [
          {
            name: 'region_includes',
            config: {
              type: 'SelectControl',
              multi: true,
              freeForm: true,
              label: t('Include only regions'),
              description: t(
                'Comma-separated ISO codes (iso_3166_2 or adm0_a3). ' +
                  'When set, only these features are rendered. Projection ' +
                  'auto-fits to the included set.',
              ),
              choices: [],
              default: [],
              renderTrigger: true,
            },
          },
        ],
        [
          {
            name: 'region_excludes',
            config: {
              type: 'SelectControl',
              multi: true,
              freeForm: true,
              label: t('Exclude regions'),
              description: t(
                'Comma-separated ISO codes to drop from the rendered map.',
              ),
              choices: [],
              default: [],
              renderTrigger: true,
            },
          },
        ],
        [
          {
            name: 'show_flying_islands',
            config: {
              type: 'CheckboxControl',
              label: t('Show flying islands'),
              description: t(
                'When on, far-flung territories (e.g. US Hawaii/Alaska) are ' +
                  'shown — usually repositioned into insets near the mainland. ' +
                  'When off, they are dropped entirely and the viewport tightens ' +
                  'to the remaining mainland.',
              ),
              default: true,
              renderTrigger: true,
            },
          },
        ],
        [
          {
            name: 'name_language',
            config: {
              type: 'SelectControl',
              label: t('Name language'),
              description: t(
                'Which language to use for displayed region names. ' +
                  "Falls back to English when the requested language isn't " +
                  'available for a feature.',
              ),
              choices: NAME_LANGUAGE_CHOICES,
              default: 'en',
              renderTrigger: true,
              clearable: false,
            },
          },
        ],
      ],
    },
    {
      label: t('Query'),
      expanded: true,
      controlSetRows: [
        [
          {
            name: 'entity',
            config: {
              type: 'SelectControl',
              label: t('ISO code column'),
              description: t(
                'Column in your dataset containing ISO codes that match ' +
                  'features in the chosen map (iso_3166_2 for subdivisions, ' +
                  'adm0_a3 for countries).',
              ),
              mapStateToProps: (state: any) => ({
                choices: (state.datasource?.columns ?? []).map((c: any) => [
                  c.column_name,
                  c.column_name,
                ]),
              }),
              validators: [validateNonEmpty],
            },
          },
        ],
        ['metric'],
        ['adhoc_filters'],
        ['row_limit'],
      ],
    },
    {
      label: t('Chart Options'),
      expanded: true,
      tabOverride: 'customize',
      controlSetRows: [
        [
          {
            name: 'number_format',
            config: {
              type: 'SelectControl',
              freeForm: true,
              label: t('Number format'),
              renderTrigger: true,
              default: 'SMART_NUMBER',
              choices: D3_FORMAT_OPTIONS,
              description: D3_FORMAT_DOCS,
            },
          },
        ],
        ['linear_color_scheme'],
      ],
    },
  ],
  controlOverrides: {
    entity: {
      label: t('ISO code column'),
      description: t(
        'Column containing ISO codes of region/province/department in your dataset.',
      ),
    },
    linear_color_scheme: {
      renderTrigger: true,
    },
  },
  formDataOverrides: formData => ({
    ...formData,
    entity: getStandardizedControls().shiftColumn(),
    metric: getStandardizedControls().shiftMetric(),
  }),
};

export default config;
